# Porta para rodar o ms-config:
quarkus.http.port=8085

my.custom.config=Este é um valor de configuração de exemplo
quarkus.config-server.enabled=true

# Esse caminho, acima, deve apontar para um diretório onde você irá armazenar os arquivos de configuração em formatos como YAML ou JSON, no meu caso foi dentro do próprio repositório do ms-config.
quarkus.config-server.config-locations=C:\\Workspace\\Person-Projects\\project-ecommerce\\ms-config\\src\\main\\java\\dev\\thallys\\ms\\config\\configs

# Configurações do banco de dados
db.kind=postgresql
db.url=jdbc:postgresql://localhost:5432/ecomproject
db.username=postgres
db.password=123456
db.driver=org.postgresql.Driver
db.min-size=5
db.max-size=20
db.acquire-timeout=30
db.validation-timeout=30

# Hibernate
hibernate.log.format-sql=true
hibernate.log.sql=true
hibernate.sql-load-script=import.sql
hibernate.database.generation=update

# Hibernate ms-carrinho
hibernate.sql-load-script.ms-carrinho=import-msCarrinho.sql
hibernate.database.generation.ms-carrinho=update

# Hibernate ms-checkout
hibernate.sql-load-script.ms-checkout=import-msCheckout.sql
hibernate.database.generation.ms-checkout=update

# Hibernate ms-produtos
hibernate.sql-load-script.ms-produtos=import-msProdutos.sql
hibernate.database.generation.ms-produtos=update

# Swagger
# ms-config:
quarkus.smallrye-openapi.info-title=Application Config Server API
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=Application Config Server in the Ecommerce in quarkus.
quarkus.smallrye-openapi.info-contact-name=Github
quarkus.smallrye-openapi.info-contact-url=https://www.github.com/thallyscezar

# ms-carrinho
swagger.info-title.ms-carrinho=Application Carrinho API
swagger.info-version.ms-carrinho=1.0.1
swagger.info-description.ms-carrinho=Application Carrinho in the Ecommerce in quarkus.
swagger.info-contact-name.ms-carrinho=Github
swagger.info-contact-url.ms-carrinho=https://www.github.com/thallyscezar

# ms-checkout
swagger.info-title.ms-checkout=Application CheckOut API
swagger.info-version.ms-checkout=1.0.1
swagger.info-description.ms-checkout=Application CheckOut in the Ecommerce in quarkus.
swagger.info-contact-name.ms-checkout=Github
swagger.info-contact-url.ms-checkout=https://www.github.com/thallyscezar

# ms-dashboard
swagger.info-title.ms-dashboard=Application DashBoard API
swagger.info-version.ms-dashboard=1.0.1
swagger.info-description.ms-dashboard=Application DashBoard in the Ecommerce in quarkus.
swagger.info-contact-name.ms-dashboard=Github
swagger.info-contact-url.ms-dashboard=https://www.github.com/thallyscezar

# ms-produto
swagger.info-title.ms-produtos=Application Produtos API
swagger.info-version.ms-produtos=1.0.1
swagger.info-description.ms-produtos=Application Produtos in the Ecommerce in quarkus.
swagger.info-contact-name.ms-produtos=Github
swagger.info-contact-url.ms-produtos=https://www.github.com/thallyscezar

## URLs de serviços externos
#external.service.url=http://api.external-service.com

# Identificador do microserviço
microservice.name=ms-config


